# Generated by Django 4.2.3 on 2023-07-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_log_be', '0003_delete_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('start_location', models.CharField(max_length=50)),
                ('end_location', models.CharField(max_length=50)),
                ('day_hours', models.FloatField(max_length=50)),
                ('night_hours', models.FloatField(max_length=50)),
                ('aircraft', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_log_be.user')),
            ],
        ),
    ]
