# name: Run tests
# on: push
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:latest
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: FlightLog
#         ports:
#           - 5432:5432
#         # needed because the postgres container does not provide a healthcheck
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#   # execute_tests:
#   #   name: Install requirements and execute tests
#   #   runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       - name: Run migrations
#         run: python manage.py migrate
#       - name: Run tests
#         run: python manage.py test